version: '3'

services:
  bleeding_edge:
    build: .
    ports:
      - 25565:25565/tcp
    volumes:
      - ./run/:/home/user/run
      - ./backups/:/home/user/backups
    restart: unless-stopped
    stdin_open: true